import type { Metadata } from "next";
import { company } from "@/lib/site";
import { SectionWrapper } from "@/components/site/section-wrapper";
import { PageIntro } from "@/components/site/page-intro";

export const metadata: Metadata = {
  title: "Legal & Privacy Policy | Acacia Labs",
  description: "Terms of service, privacy policies, and infrastructure guidelines for Acacia Labs.",
  alternates: {
    canonical: `${company.url}/legal`,
  },
};

export default function LegalPage() {
  return (
    <div className="bg-primary-bg min-h-screen pt-32 pb-24 overflow-hidden">
      <PageIntro 
        eyebrow="LEGAL" 
        title="Privacy & Infrastructure Policies." 
        description="The legal and data security frameworks governing the use of Acacia Labs systems."
      />
      
      <SectionWrapper>
        <div className="max-w-3xl mt-16 space-y-12 text-sm text-text-secondary leading-relaxed">
          
          <div className="space-y-4">
            <h2 className="text-xl font-bold uppercase tracking-tight text-text-primary">1. Data Security & Sovereignty</h2>
            <p>
              Acacia Labs engineers high-availability systems with strict adherence to data sovereignty principles. We do not sell, distribute, or unethically utilize operational data generated by enterprise clients. Financial ledgers and operational metadata remain encrypted and logically separated within our infrastructure.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-xl font-bold uppercase tracking-tight text-text-primary">2. Infrastructure Reliability</h2>
            <p>
              Our systems are deployed with an objective of 99.99% uptime. However, given the structural realities of African carrier networks and mobile money pipelines, certain latency and execution failures may occur due to third-party infrastructural downtime. We mitigate this through robust queuing and offline-first consensus logic, but we are not legally liable for external network failures.
            </p>
          </div>

          <div className="space-y-4">
            <h2 className="text-xl font-bold uppercase tracking-tight text-text-primary">3. Operational Accountability</h2>
            <p>
              While Acacia Labs provides intelligent automation and decision-support systems, final execution and financial accountability rest with the enterprise operator. Our AI integrations are designed to surface insights and orchestrate routine tasks, but human-in-the-loop verification is mandated for critical financial deployments.
            </p>
          </div>

          <div className="border-t border-glass-border/40 pt-8 mt-12 text-xs">
            <p>Last updated: May 2026</p>
            <p className="mt-2">For detailed Terms of Service, compliance documents, or security whitepapers, please contact <a href={`mailto:${company.email}`} className="text-accent-cyan hover:underline">{company.email}</a>.</p>
          </div>

        </div>
      </SectionWrapper>
    </div>
  );
}
